### ISSUE TITLE
command-palette:toggle not working

### ISSUE THREAD

**Issue by croaker000** [suda/tool-bar#105]
Atom 1.4, linux.

Using tool-bar-main template, clicking the command-palette:toggle button doesn't do anything. Atom "flashes" as if it's trying to do something - no command palette appears though.

Command palette works from Atom's main menu and ctrl-shift-p

**Comment by jerone** [comment]
Confirmed on Windows with Atom 1.5.0-beta1 too.

It has something to do with the focused element. @cakecatz You did something with this in the past: https://github.com/suda/tool-bar/pull/36. Any ideas?

**Comment by jerone** [comment]
Did some research. `command-pallette:toggle` is [attached](https://github.com/atom/command-palette/blob/master/lib/command-palette-view.coffee#L17) to Atoms workspace. But [according to the docs](https://atom.io/docs/api/v1.4.1/CommandRegistry#instance-dispatch) executing a command to any element the event should bubble up the tree. 

The following code dispatches the command correctly with the correct target:
```console
> atom.commands.dispatch(atom.views.getView(atom.workspace), 'command-palette:toggle')
< true
```

But when I try any other element on the same tree it fails:
```console
> atom.commands.dispatch(atom.workspace.getActiveTextEditor(), 'command-palette:toggle')
< false
```

While the following code works:
```console
> atom.commands.dispatch(atom.views.getView(atom.workspace.getActiveTextEditor()), 'command-palette:toggle')
< true
```

**Comment by jerone** [comment]
Think I found a [solid solution](https://github.com/jerone/tool-bar/tree/issues/105-fix-focus). Once PR#106 is merged, I'll open a PR to fix this.
