### ISSUE TITLE
don't support icon : logo-gist  (octicons)

### ISSUE THREAD

**Issue by kumiao** [suda/tool-bar#124]
don't support icon : logo-gist  (octicons)

**Comment by jerone** [comment]
Confirmed. However the [Octicons](https://octicons.github.com/) are [supplied](https://github.com/suda/tool-bar#supported-icon-sets) by Atom itself and it [looks like](https://github.com/atom/atom/commit/414284563266cc77ec1e41b29a583ca8ac1a1fa6) they have a very outdated version of the font. I would suggest that you [open an issue](https://github.com/atom/atom) at their repo.

**Comment by jerone** [comment]
Upstream: https://github.com/atom/atom/issues/8314
