### ISSUE TITLE
The only icon that shows up is the run button

### ISSUE THREAD

**Issue by d3f4alt** [suda/tool-bar#126]

**Comment by jerone** [comment]
Please provide some more information! What steps have you done, which packages have you installed, what versions, etc...?

**Comment by d3f4alt** [comment]
I installed this using the love-2d ide package and it is version 0.3.0, I
will have all the packages in the love-2d ide plus a code minimap

**Comment by jerone** [comment]
As you can read on the [second paragraph of the readme](https://github.com/suda/tool-bar#readme), this package by itself adds an empty toolbar. To propagate it with icons you can install plugins. One of those plugins is apparently the [love-ide](https://atom.io/packages/love-ide) package. Which, [as stated on their readme](https://github.com/rameshvarun/love-ide#run-icon-in-toolbar), adds just one button, the run button! If you want more buttons, you have to install other [plugins](https://github.com/suda/tool-bar#plugins).
