### ISSUE TITLE
What is the full set of supported icons?

### ISSUE THREAD

**Issue by brkeh** [suda/tool-bar#128]
Hello

I am trying to create a toolbar with a save button. I tried using https://atom.io/packages/tool-bar. Then I tried using https://atom.io/packages/flex-tool-bar1. I can't find a list of the icons available by default in Flex tool bar though.

Is there a list of all the icons supported or even just an icon that represents save?

Thanks very much

Brendan

**Comment by lexcast** [comment]
*   [Octicons](https://octicons.github.com) (Atom's flavour)
*   [Ionicons](http://ionicons.com) (`ion`)
*   [FontAwesome](http://fortawesome.github.io/Font-Awesome) (`fa`)
*   [Foundation](http://zurb.com/playground/foundation-icon-fonts-3) (`fi`)
*   [IcoMoon](https://icomoon.io) (`icomoon`)
*   [Devicon](http://devicon.fr) (`devicon`)
*   [MaterialDesignIcons](https://materialdesignicons.com/) (`mdi`)

Maybe something like this with flex-toolbar
```cson
[
  {
    type: "button"
    icon: "floppy-o"
    callback: "core:save"
    tooltip: "Save"
    iconset: "fa"
  }
]
```

**Comment by brkeh** [comment]
Thanks lexcast. I didn't know about iconset. I'll try that

**Comment by jerone** [comment]
It is used in the [examples](https://github.com/cakecatz/flex-toolbar#example) of Flex Tool Bar and [documented](https://github.com/suda/tool-bar#supported-icon-sets) by Tool Bar package. But I [agree](https://github.com/cakecatz/flex-toolbar/issues/59) that this part could be better documented at Flex Tool Bar.

Closing in favor off https://github.com/cakecatz/flex-toolbar/issues/59

**Comment by brkeh** [comment]
I see that now Jerone. I assume [Octicons](https://octicons.github.com/) is the default set when `iconset` is not specified and the `iconset` property is mandatory for any set other than Octicons. It think this needs to be highlighted though. It might be more an issue for Flex Tool Bar and downstream projects than the [tool-bar](https://github.com/suda/tool-bar) project.

Thanks very much

Brendan
