### ISSUE TITLE
[WIP] Update plugin to new provider service

### ISSUE THREAD

**Issue by jerone** [suda/tool-bar#141]
I think it's nice to let plugin developers know that there's a new provider service available so we can remove the legacy code as soon as possible. Besides that, the previously documented provider semver won't support the new version we're releasing.

There are two lists of plugins:

1. Plugins that consume the service and the public API.
2. Plugins that consume the service and use the return type.

List one:

- [x] [Menu Manager](https://atom.io/packages/menu-manager) :arrow_right: https://github.com/jerone/menu-manager/pull/4
- [x] [Tool Bar Main](https://github.com/suda/toolbar-main/) :arrow_right: https://github.com/suda/toolbar-main/pull/15
- [ ] [Toolbar Almighty](https://github.com/varemenos/atom-toolbar-almighty) :arrow_right: https://github.com/varemenos/atom-toolbar-almighty/pull/15
- [x] [Particle Dev](https://github.com/spark/particle-dev) :arrow_right: https://github.com/spark/particle-dev/pull/150
- [x] [PlatformIO IDE](https://github.com/platformio/platformio-atom-ide) :arrow_right: https://github.com/platformio/platformio-atom-ide/pull/130
- [x] [Toolbar Shortcuts](https://github.com/JostCrow/atom-toolbar-shortcuts) :arrow_right: https://github.com/JostCrow/atom-toolbar-shortcuts/pull/5
- [x] [Tool Bar Atom](https://github.com/jeselxe/tool-bar-atom) :arrow_right: https://github.com/jeselxe/tool-bar-atom/pull/7
- [x] [Toolbar for Markdown-Writer](https://github.com/zhuochun/tool-bar-md-writer)
- [ ] [toolbar-basic](https://github.com/mattlovaglio/toolbar-basic) :arrow_right: https://github.com/mattlovaglio/toolbar-basic/pull/1
- [x] [atom-toolbar-config](https://github.com/MunGell/atom-toolbar-config) :arrow_right: https://github.com/MunGell/atom-toolbar-config/pull/1
- [ ] [atom-vital-tool-bar](https://github.com/taronpa/atom-vital-tool-bar) :arrow_right: https://github.com/taronpa/atom-vital-tool-bar/pull/1
- [x] [bloginatom](https://github.com/hevnly/bloginatom) :arrow_right: https://github.com/hevnly/bloginatom/pull/2
- [ ] [Toolbar Ioton](https://github.com/iotontech/ioton-atom) :arrow_right: https://github.com/iotontech/ioton-atom/pull/1
- [ ] [awesome-tool-bar](https://github.com/radjivC/awesome-tool-bar) :arrow_right: https://github.com/radjivC/awesome-tool-bar/pull/1
- [ ] [toolbar-iconshortcuts](https://github.com/thiagolucio/toolbar-iconshortcuts) :arrow_right: https://github.com/thiagolucio/toolbar-iconshortcuts/pull/2
- [ ] [atom-toolbar-besser](https://github.com/besser/atom-toolbar-besser) :arrow_right: https://github.com/besser/atom-toolbar-besser/pull/1
- [ ] [bgc tool bar](https://github.com/bgc/tool-bar-bgc) :arrow_right: https://github.com/bgc/tool-bar-bgc/pull/1
- [ ] [hayatan-tool-bar](https://github.com/hayatan/atom-hayatan-tool-bar) :arrow_right: https://github.com/hayatan/atom-hayatan-tool-bar/pull/1
- [ ] [Atom Electric Imp Tools](https://github.com/deldrid1/atom-imp-tools) :arrow_right: https://github.com/deldrid1/atom-imp-tools/pull/1
- [ ] [love-ide](https://github.com/rameshvarun/love-ide) :arrow_right: https://github.com/rameshvarun/love-ide/pull/17

List two:

- [ ] [Flex Tool Bar](https://github.com/cakecatz/flex-toolbar) :arrow_right: https://github.com/cakecatz/flex-toolbar/commits/coffee-to-es6
- [x] [Nuclide](https://github.com/facebook/nuclide) :arrow_right: https://github.com/facebook/nuclide/commit/173f26ea93c956b465f517eb89d962e75071b7f2
- [ ] [Atom-macros](https://github.com/pbihler/atom-macros) (in an invalid [way](https://github.com/pbihler/atom-macros/blob/master/lib/macros.coffee#L69) btw) :arrow_right: https://github.com/pbihler/atom-macros/issues/8

~~This is a work in progress as there are way more [plugins](https://github.com/suda/tool-bar#plugins) available.~~ List seems complete for the moment.

Ref https://github.com/suda/tool-bar/issues/135, https://github.com/suda/tool-bar/pull/136, https://github.com/suda/tool-bar/pull/140.

**Comment by zertosh** [comment]
Nuclide does tuesday releases (internally and open-source), so if you publish the new tool-bar on Monday morning, then that gives me a day to update. This would be the ideal case.

**Comment by jerone** [comment]
I'm going to hold of publishing for a little bit. This issue was opened to get a list of plugins using the tool-bar API and informing them of the changes before releasing the package. The list was summarized out of the top of my head, but requires some more research. The idea right now is to update the list, at least informing the package authors and maybe sending an PR.

**Comment by jerone** [comment]
Can someone confirm that using `^0 || ^1` is the correct semver range for using in the new [service provider](https://github.com/suda/tool-bar/blob/master/README.md#packagejson)...

/cc @suda @cakecatz @zertosh

**Comment by zertosh** [comment]
Yeah...

```js
require('semver').toComparators('^0 || ^1')
// [ [ '>=0.0.0', '<1.0.0' ], [ '>=1.0.0', '<2.0.0' ] ]
```

**Comment by jerone** [comment]
Thanks for the confirmation on the ranges. Some explanation. Previously we had `^0.1.0` but I learned that that would only select `>=0.1.0 <0.2.0`. For 1.0.0 I want to make sure we get all new minor updates too. Seems valid I think.

**Comment by zertosh** [comment]
Yup. See https://github.com/npm/node-semver#caret-ranges-123-025-004

> [Caret Ranges allow] changes that do not modify the left-most non-zero digit in the `[major, minor, patch]` tuple. In other words, this allows patch and minor updates for versions `1.0.0` and above, patch updates for versions `0.X >=0.1.0`, and no updates for versions `0.0.X`.

**Comment by jerone** [comment]
Because of the very hard work and if you agree, I like you to add to the list of [contributors on the readme](https://github.com/suda/tool-bar#contributors).

In https://github.com/suda/tool-bar/pull/140#issue-154883976 you mentioned that there is room for improvements and performance. I'm especially interested in your thoughts about performance improvements.

**Comment by zertosh** [comment]
Thanks @jerone! 😄

**Comment by zertosh** [comment]
@jerone as far as perf:

1. Dynamically load the stylesheets for the icon sets you use. This will cut the startup time in half.
2. Debounce with `requestAnimationFrame` the resize and scroll events.
3. Insert the initial buttons in a single batch. Right now you're forcing a relayout for every button at startup. Really expensive.

**Comment by jerone** [comment]
1. This is an important one! The iconsets are "huge", so if we can somehow lazy load those files the startup time would indeed decrease. Besides that point, I can also see conflicts with other packages, when they load those iconsets too.
2. Both scroll on the tool-bar and resize on the window won't happen that much, but still it's an good idea to debounce those events.
3. Aldo I see the benefit of this (forcing redraw events), I don't see how we can improve this. At anytime it's possible to `addItem` to the tool-bar, not only at startup (or when the service is called).

**Comment by zertosh** [comment]
> Both scroll on the tool-bar and resize on the window won't happen that much, but still it's an good idea to debounce those events

I resize my window a lot - probably because I'm always opening/closing the devtools. This is easy to fix though.

> Aldo I see the benefit of this (forcing redraw events), I don't see how we can improve this. At anytime it's possible to addItem to the tool-bar, not only at startup (or when the service is called).

I'm only concerted with batching the DOM updates during the Atom package activation cycle. We put 13 buttons on the tool-bar - that's a lot of redrawing. I'm on a mission to reduce start up time :)

<img width="40" alt="vwtmc" src="https://cloud.githubusercontent.com/assets/830952/15476989/3f8bfcc2-20c7-11e6-8090-e4e3e4c0f4e5.png">

**Comment by zertosh** [comment]
Any word on publishing the space-view-less update?

**Comment by jerone** [comment]
[**@zertosh**](https://github.com/zertosh) commented on [8 jun. 2016 23:47 CEST](https://github.com/suda/tool-bar/issues/141#issuecomment-224739662 "2016-06-08T21:47:47Z - Replied by Github Reply Comments"):
> Any word on publishing the space-view-less update?

Before publishing the package with the awesome new changes we need to contact all plugins (send PR) so they have time to react on the breaking changes. I've already started to research some plugins above, but the list is not yet finished.
Currently I'm to busy to finish the list and send PR's. But in 1,5 week I have some vacation time to spend on this issue.

I would be great if others could help. /cc @suda @cakecatz

**Comment by jerone** [comment]
@cakecatz Do you have time to update Flex Tool Bar with the latest API changes ... so it's compatible when we release then new Tool Bar package.

**Comment by jerone** [comment]
Half of above mentioned packages are ready for a new Tool Bar release, with remaining package on very low install counts.

I plan on releasing a new version this Sunday.

@zertosh @cakecatz Any objections?

**Comment by zertosh** [comment]
@jerone We're good on my side! Thanks!

**Comment by jerone** [comment]
![giphy](https://cloud.githubusercontent.com/assets/55841/16545990/9ed53fd8-413b-11e6-9435-1a98957c3251.gif)

**Comment by cakecatz** [comment]
> Do you have time to update Flex Tool Bar with the latest API changes ... so it's compatible when we release then new Tool Bar package.

@jerone Sorry, I had no time to do that... 😫😫😫
But I will working for it from today 💪

**Comment by jerone** [comment]
Closing, as all plugins have been notified and/or updated.

**Comment by jerone** [comment]
@cakecatz Almost 5 months after removing space-pen dependency and switching to ES6, it's time to **merge #153** and remove all legacy code. The only thing blocking this is the Flex Toolbar package still running on the old API (most noticeable packages have already [switched](https://github.com/suda/tool-bar/issues/141#issue-154932717)). Once merged, Flex Toolbar will completely **stop working**. I noticed you already made an attempt to upgrade on a [different branch](https://github.com/cakecatz/flex-toolbar/commits/coffee-to-es6). Is there any change to speed up this process?

/cc @zertosh

**Comment by zertosh** [comment]
@jerone, we're all good on my end

**Comment by cakecatz** [comment]
@jerone Hi! I pushed commit for support new tool-bar provider just now.

**Comment by jerone** [comment]
@cakecatz Great! Do you want me to test? I probably have some spare time tonight.

**Comment by cakecatz** [comment]
@jerone Yes please 🙏

**Comment by jerone** [comment]
[**@cakecatz**](https://github.com/cakecatz) commented on [7 sep. 2016 12:15 CEST](https://github.com/suda/tool-bar/issues/141#issuecomment-245237077 "2016-09-07T10:15:43Z - Replied by Github Reply Comments"):
> @jerone Yes please 🙏

Just tested your latest commit with #153 and it worked with my configuration. Let me know when you released Flex Tool Bar, so I can merge #153.

**Comment by cakecatz** [comment]
@jerone Thanks!
I'll release now 🚢

**Comment by thiagolucio** [comment]
Hi Jerone. 
So..i correct the package last Saturday Night. Thanks to warning. I think ok now. The package is:
"toolbar-iconshortcuts"
Thanks Again.
