### ISSUE TITLE
Toolbar not visible

### ISSUE THREAD

**Issue by NerdPad** [suda/tool-bar#142]
The toolbar doesn't show up at all. How can I help you debug this?

**Comment by jerone** [comment]
This package by itself [doesn't](https://github.com/suda/tool-bar#atom-tool-bar) add any buttons as it's a service for other package to consume and append their own buttons. You can install one of the [plugins](https://github.com/suda/tool-bar#plugins) to propagate the toolbar with icons.

**Comment by jerone** [comment]
Closing as probably invalid.

**Comment by kendrickdk** [comment]
How do you add buttons?

**Comment by suda** [comment]
@kendrickdk you need to install some [plugins](https://github.com/suda/tool-bar#plugins) like Jerone mentioned above.

**Comment by kendrickdk** [comment]
I figured it out... I just installed his other plugin that had the main
buttons already in it.  TY.
