### ISSUE TITLE
Full-width tool bar screws up `atom/tree-view` scrolling

### ISSUE THREAD

**Issue by phoenixenero** [suda/tool-bar#146]
Originally posted on:

<https://github.com/atom/tree-view/issues/844>

## Issue

Double-clicking items in `tree-view` have delayed events when tool bar is enabled to run the full width.

Here's a video showing the issue:
https://gfycat.com/AdeptWelcomeCoqui

Sorry, tool bar not that visible since I thought tree-view was the problem. It's right at the top of the video.

## Workaround

Disable full-width.

**Comment by jerone** [comment]
Sorry to hear that you are having problems with the tool-bar package.

Right now I can't reproduce your problem. Can you at least provide us with some information about which versions you are running (e.g. Atom, package, OS, etc...). Besides that, to add buttons on the tool-bar you need a plugin, which plugin are you running? Also can you reproduce this issue with all other community packages disabled (to be sure no other package is in the way).

**Comment by phoenixenero** [comment]
Aaaand now I have to close this one because it's apparently a `cakecatz/flex-tool-bar` issue. I don't have the issue with `suda/tool-bar-main` enabled **even if** `flex-tool-bar is enabled. Only when I have `flex-tool-bar` enabled by itself does the issue appear.

### For completeness:

To reproduce the issue:

1. install `flex-tool-bar`
1. Add random stuff to `flex-tool-bar` config
1. Disable all tool-bar community packages except `flex-tool-bar`
1. Set `tool-bar` to horizontal full-width.
1. Open a project with tons of directories and files.
1. Scroll `tree-view` to the very bottom
1. Click or double-click a file in `tree-view`
