### ISSUE TITLE
Toolbar show in dependence of mime type of content

### ISSUE THREAD

**Issue by horosgrisa** [suda/tool-bar#150]
For example: I use [tool-bar-markdown-writer](https://atom.io/packages/tool-bar-markdown-writer), but if I edit non-markdown text, this toolbar remain visible, but it make no sense.
![screenshot_20160704_170420](https://cloud.githubusercontent.com/assets/4980269/16563209/5c6fb5a0-4209-11e6-831f-8db049c2bf45.png)
You can add posibility to show/destroy toolbar in dependence of content?

**Comment by jerone** [comment]
This is an issue for tool-bar-markdown-writer. That package needs to detect if an file is an actual markdown file and only then add buttons. [Flex Tool Bar has something similar](https://github.com/cakecatz/flex-toolbar#hideshow-disableenable-button). Even looks like someone [suggested it](https://github.com/zhuochun/tool-bar-md-writer/issues/1).

**Comment by zhuochun** [comment]
@horosgrisa should have solved in the new release. Feel free to submit issues if any at https://github.com/zhuochun/tool-bar-md-writer/issues

@jerone thanks for the suggestions.
