### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by ngryman** [suda/tool-bar#152]
Hi,

Why not proposing a `json` configuration file alternative to the `api`?
Also this file could be used directly with your plugin to create a custom toolbar easily, instead of having to either install other plugins or create one.

Thanks!

**Comment by ngryman** [comment]
Basically include the features of: https://github.com/MunGell/atom-toolbar-config/tree/master/lib.

**Comment by jerone** [comment]
Thank you for your feedback.

The intent of this package is only to provide a service API. 

There are [more plugins](https://github.com/suda/tool-bar#plugins) providing a structure you've mentioned, starting with [Flex Tool Bar](https://atom.io/packages/flex-tool-bar).

**Comment by ngryman** [comment]
@jerone May I ask why? Just because I'm curious. I don't see the point of providing an empty shell plugin.

**Comment by jerone** [comment]
I can't say for sure, but this package was originally written for [Particle Dev](https://atom.io/packages/particle-dev). Together with [SoC](https://en.wikipedia.org/wiki/Separation_of_concerns) and providing a public API, I see good reasons to keep this package clean and simple. @suda, correct me if I'm wrong.
