### ISSUE TITLE
More of a suggestion than an issue

### ISSUE THREAD

**Issue by NJseo** [suda/tool-bar#155]
Thankyou for committingyour time to this project, its great. I was wondering or hoping that you would add chmod permissions to the options that are available.

Great work

**Comment by jerone** [comment]
How do you mean?

**Comment by NJseo** [comment]
How to do I set the file permissions on the remote server, per file or directory?

**Comment by NJseo** [comment]
Also, what would be cool is the pallete was dockable to other windows.

**Comment by jerone** [comment]
Are you sure you've got the correct repo?!

The tool-bar package for Atom doesn't have any permissions and pallette.


Please ellobrate about what you mean with those feature requests...






On Thu, Aug 4, 2016 at 6:22 PM +0200, "John" <notifications@github.com> wrote:





Also, what would be cool is the pallete was dockable to other windows.

---

**Comment by NJseo** [comment]
Your right, my bad. I was looking for atom-commander.
