### ISSUE TITLE
Icon size not saving

### ISSUE THREAD

**Issue by FetzenRndy** [suda/tool-bar#168]
The Icon size for my tool-bar is not saving, everytime I restart atom I need to set it to the value I like.

Maybe its an issue with my editor since it also doesn't save disabled packages but everything besides that works fine

**Comment by jerone** [comment]
Saving icon size is done through Atom's Settings package, this package doesn't handle that.  Your `config.cson` file should contain `"tool-bar": iconSize: "16px"` (or any value).

You mentioned something else being broken with the Settings package. Maybe it's related. Have you tried updating/resetting Atom?

**Comment by FetzenRndy** [comment]
Thanks this solved it... I didn't know that this package doesn't handle saving the settings, I thought It was just my editor not saving...

SOLVED
