### ISSUE TITLE
allow multiple commands in an array

### ISSUE THREAD

**Issue by UziTech** [suda/tool-bar#170]

**Comment by jerone** [comment]
What would be an use-case?

**Comment by UziTech** [comment]
[flex-toolbar](https://github.com/cakecatz/flex-toolbar#multiple-callback) currently allows this however they don't allow it with modifier keys (ctrl, alt, shift)

[remote-ftp](https://github.com/mgrenier/remote-ftp) shows a tree-view like pane for remote files so I have a button to toggle the pane and connect and when holding `ctrl` it toggles the pane and disconnects

```javascript
callback: {
  "": ["remote-ftp:toggle", "remote-ftp:connect"],
  "ctrl": ["remote-ftp:toggle", "remote-ftp:disconnect"]
}
```

**Comment by UziTech** [comment]
I was going to submit a pull request to flex-toolbar but it seemed easier to add arrays to tool-bar rather than add modifier keys to flex-toolbar

**Comment by asci** [comment]
hey, any idea why this is not working:
```js
    callback: ['pane:split-right', 'window:move-active-item-to-pane-on-right']
```

I'm using lastest Atom and `tool-bar` 1.0.1
