### ISSUE TITLE
Programmatically disabling hiding the toolbar

### ISSUE THREAD

**Issue by vjeux** [suda/tool-bar#172]
We use this awesome plugin for [Nuclide](https://nuclide.io/), Facebook IDE built-on top of Atom, in order to display all the features. However, from time to time, engineers find a way to accidentally hide the toolbar and struggle to put it back up.

We would like to disallow people from being able to hide the toolbar. I'd be happy to implement the feature but I figured I would open an issue first in order to see if you'd likely want the feature and have suggestions on how to design the API for it :)

cc @suda 

Thanks!

**Comment by jerone** [comment]
There are currently multiple ways to "hide" the Tool Bar in Atom:
* Settings > Tool Bar > uncheck "Visible" option
* Menu bar > "Packages" menu-item > "Tool Bar" > "Toggle Tool Bar"
* Context-menu on tool-bar > "Toggle Tool Bar"
* Command `tool-bar:toggle`
* Hide with css

I'm really :-1: on removing the option to let the user choose to hide the Tool Bar, as that will also affect Atom's users.

If you really set on disabling hiding the Tool Bar, my suggestion would be for Nuclide to listen on the `tool-bar:toggle` command (that's what all options listed above, except css, use) and revert the users choose.

How would you propose to disable hiding the Tool Bar?

**Comment by vjeux** [comment]
My suggestion would be where we do `toolbar.addButton(...)` add another call `toolbar.disableHideability()` (I don't particularly care about the exact naming).

**Comment by vjeux** [comment]
I thought about listening to `tool-bar:toggle` command but it still shows the option in all the places you mentioned so it would be a sub-optimal user experience for people to see the option to hide it and then Nuclide saying: actually, no!

For context, we install Nuclide and therefore tool-bar by default on all Facebook engineers laptop. So, they don't think of tool-bar as a separate package but more as the place where there are all the Nuclide buttons.

**Comment by vjeux** [comment]
Thanks for the quick reply :)

**Comment by vjeux** [comment]
The other alternative I'm considering is to implement a basic version of toolbar that can only be shown on the left and only supports Nuclide's specific needs, but I'd rather not if I don't have to :)

**Comment by jerone** [comment]
Thinking about this more and I really don't like the idea of packages deciding if it should be visible or not (specially in Atom). Especially as I'm working on the [next feature](https://github.com/suda/tool-bar/pull/163) where users can decide which plugins are allowed to attach buttons.

Of course I don't want to lose Nuclide as one of the biggest plugin!
Another solution is to watch the Tool Bar for visibility and show a friendly message to users when they try to hide it.

/cc @zertosh

**Comment by vjeux** [comment]
Thanks for the quick response!

I've created a fb-only package as you suggested to always make sure that the toolbar is visible. I will try to drive it internally for now and if it's successful then come back to you to ask for a real fix :)

```js
class Activation {
  enforceToolBarDisplayed() {
    setImmediate(() => {
      const workspace = atom.views.getView(atom.workspace);
      if (!workspace.querySelector('.tool-bar')) {
        atom.commands.dispatch(workspace, 'tool-bar:toggle');
      }
    });
  }

  constructor() {
    this._disposables = new CompositeDisposable(
      atom.commands.add(
        'atom-workspace',
        // eslint-disable-next-line nuclide-internal/atom-commands
        'tool-bar:toggle',
        this.enforceToolBarDisplayed,
      ),
    );

    this.enforceToolBarDisplayed();
  }
}
```
