### ISSUE TITLE
Ability to rotate icons

### ISSUE THREAD

**Issue by HyperHamster** [suda/tool-bar#173]
This could be solved by adding a new `iconrotate` property to button and url types.

It may be problematic to allow degrees of rotation instead it could work by having four 90° increments by taking a value from 0 to 3. Such as 0 = 0° (Default), 1 = 90°, 2 = 180°, 3 = 270°.

Use-case example:
```
[
    {
        type: "button"
        callback: "pane:split-right"
        iconset: "fa"
        icon: "columns"
    }
    {
        type: "button"
        callback: "pane:split-down"
        iconset: "fa"
        icon: "columns"
        iconrotate: "1"
    }
]
```

**Comment by jerone** [comment]
I think you want to propose this feature to [Flex Tool Bar](https://github.com/cakecatz/flex-toolbar) package.

**Comment by HyperHamster** [comment]
Sorry about that @jerone , I must have got redirected to this repository by accident.

**Comment by jerone** [comment]
No problem.

For reference: https://github.com/cakecatz/flex-toolbar/issues/89
