### ISSUE TITLE
Showing labels

### ISSUE THREAD

**Issue by Zambiorix** [suda/tool-bar#176]
Hi,

This is feature request.
Is it possible to show labels next to icons? (maybe with a size limit)
Labels could be positioned left, top, right or bottom relative to the icon, on a global or per-entry setting?

Would useful I believe..
Thanks!

Cheers
Gerd

**Comment by jerone** [comment]
I'm closing this as duplicate of https://github.com/suda/tool-bar/issues/43. Please read from https://github.com/suda/tool-bar/issues/43#issuecomment-199403194 about custom buttons (for example labels).
