### ISSUE TITLE
Default iconset handling

### ISSUE THREAD

**Issue by idleberg** [suda/tool-bar#193]
I just came across [this question](https://discuss.atom.io/t/flex-tool-bar-icon-setting/42039) on the Atom forums, where a user wondered why his settings for `tool-bar` did not work.

```cson
{
    type: "button"
    icon: "arrow-down"
    callback: 'core:save'
    tooltip: "save"
    iconset: "octicons" # this does not work
  }
```
The reason why this doesn't work is that Octicons are default and need (and should) not be specified explicitly. When it is specified, no icon is displayed. IMHO, specifying `octicons` and omitting the `iconset` setting altogether should have the same effect.

**Comment by Pyragon** [comment]
Fixed in #194
