### ISSUE TITLE
Touch bar support

### ISSUE THREAD

**Issue by newelement** [suda/tool-bar#212]
I like the new touch bar support, but I'm seeing some odd things. The icons are changing each time I perform an action within Atom and that is causing a bit of lag within the app. Keep up the good work! Almost there with touch bar support.

**Comment by suda** [comment]
Hi Don! Glad you like it! Could you maybe capture a video of this bug so we could investigate?

**Comment by Suplanus** [comment]
Same here, video attached. It freezes atom completely for seconds...
The video shows how switch between settings tab and a markdown file with [markdown-Tool-Bar](https://atom.io/packages/tool-bar-markdown-writer)
[Video 08.01.18, 13 02 32.mov.zip](https://github.com/suda/tool-bar/files/1611439/Video.08.01.18.13.02.32.mov.zip)

**Comment by suda** [comment]
Thanks for the video! FIY if it freezes Atom you could try turning off the Touch Bar support in package settings. Maybe this would help until the fix is done.

**Comment by Suplanus** [comment]
Thanks. 
I see no setting in the UI of atom, or its only possible in the package it self?

**Comment by suda** [comment]
@Suplanus I meant the package settings in Atom's UI:

![screenshot 2018-01-08 14 20 46](https://user-images.githubusercontent.com/25722/34672573-46721106-f47f-11e7-86a5-4498badc456f.png)

But I just released [1.1.2](https://github.com/suda/tool-bar/releases/tag/v1.1.3) which should solve this issue.

**Comment by Suplanus** [comment]
🤦‍♂️ i was blind...
Thanks for the fast fix!

**Comment by newelement** [comment]
Working great now on 1.1.3. This is awesome. Big thanks!
