### ISSUE TITLE
touchbar slows down atom when there is no touchbar

### ISSUE THREAD

**Issue by UziTech** [suda/tool-bar#213]
Can we default the option to use the touchbar to false on systems that do not have a touchbar?

It slows down switching files quite a bit on Windows.

Is it possible to use electrons touchbar api to check if the touchbar is available?

Or could we disable the option on non-darwin systems?

**Comment by suda** [comment]
Oh I'm sorry to hear that. I did test it on a MacBook without Touch Bar and there was no slow downs. I'll look into the Windows issue. There is option to disable the Touch Bar:

![screenshot 2018-01-08 14 20 46](https://user-images.githubusercontent.com/25722/34672573-46721106-f47f-11e7-86a5-4498badc456f.png)

Does this option removes the speed issues?

As for the checking if the Touch Bar is available, Electron API doesn't provide an accessible method to do this but I guess it should be doable using some API or at least disable on non-darwin systems like you suggested.

**Comment by UziTech** [comment]
ya unchecking the setting fixes the issue but it took a few hours of debugging to figure out why it suddenly slowed down since it is on by default and there is no way of knowing that this setting was available when updating all of the atom packages.

It might have been better to default it to false to keep the old functionality and let people enable it if they look for it.

**Comment by suda** [comment]
I just released 1.1.4 which disables it for non-Darwin systems as other MacBooks don't seem to be affected.

**Comment by UziTech** [comment]
Thank you for the quick response ⚡️ 💯
