### ISSUE TITLE
Failed to load the tool-bar package

### ISSUE THREAD

**Issue by RohinSequeira** [suda/tool-bar#214]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 4.4.14 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [tool-bar](https://github.com/suda/tool-bar) package 1.1.4

### Stack Trace

Failed to load the tool-bar package

```
At Cannot match against 'undefined' or 'null'.

TypeError: Cannot match against 'undefined' or 'null'.
    at /packages/tool-bar/lib/touch-bar-manager.js:2:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/tool-bar/lib/tool-bar.js:3:25)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
     -0:20.2.0 commit-live-welcome:show-dashboard (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
greyatom-ide-background-tips 0.0.3 
greyatom-ide-welcome 0.0.9 
tool-bar 1.1.4 
```

**Comment by suda** [comment]
Hi! I'm looking at the Atom/Electron version and it seems very off:
**Atom:** 4.4.14 x64 such version doesn't exist (the latest is 1.24.0-beta2).
**Electron:** 1.3.13 indicates a very old version of Atom.

Could you install the latest version of Atom and see if it helped?

**Comment by yoh-there** [comment]
Same here after auto-update tool-bar, though on Ubuntu 1.17.0.x64

**Comment by suda** [comment]
@yoh-there could you post your Atom version?

**Comment by yoh-there** [comment]
Sorry, my bad for omitting a comma:

on Ubuntu (16.04LTS), Atom version 1.17.0.x64

**Comment by suda** [comment]
@yoh-there thank you! Is there a reason you're not running latest Atom (1.23.2)? 1.17.0 is almost a year old (released on 16 May 2017).

**Comment by yoh-there** [comment]
Not at all. AFAIR I just took it from the Ubuntu listed repositories when I needed Platformio, and it lever came up for auto update

**Comment by suda** [comment]
Oh I would suggest updating Atom then. The missing API that causes this issue has landed in stable Atom over six months ago. It comes with [many improvements](http://blog.atom.io/) since the version you're having.

**Comment by yoh-there** [comment]
OK. Bottom line is though, people following the lazy route that I took, will have this nasty popup, whoever's is to blame so to say; it's not an isolated case it seems which is why I chipped in.

I noticed that the Ubuntu "store" lists 1.7.0. Oy! Thanks for the effort.

**Comment by michael-andreuzza** [comment]
Hej, i had this problem also.
After a couple of days I decided to uninstall the tool-bar and install it again, it work perfectly...

have a nice one.

**Comment by gnkarn** [comment]
same problem , on mac OS X

**Comment by talkingbeast** [comment]
same problem on linux mint 18,sucks

**Comment by nooitaf** [comment]
linux mint 18.2 here too...
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
got the `.deb` from atom.io and installed manually to..
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
now it can find that `TouchBarButton` and the error is gone ;)

Is it possible to cap versions in atom packages? or is it too late for that :(

**Comment by nooitaf** [comment]
I was (as a lot of lazies are) waiting for an update of this package to fix the issue. 

You could unpublish the last ones who contain the `TouchBarButton` and then release a new version with a higher cap, maybe `>=1.22.0` ? 
https://github.com/suda/tool-bar/blob/5caf3cd5429d59d124cb3f1c62081615a3d956f0/package.json#L27-L29

**Comment by talkingbeast** [comment]
@nooitaf  i uninstall atom and reinstall atom,problem solved,i know ,a bad way to solve this nasty problem.
