### ISSUE TITLE
Failed to load the tool-bar package after 1.1.5 update

### ISSUE THREAD

**Issue by MaxGraey** [suda/tool-bar#219]
### **Atom Version**
1.23.3

### **UI Theme**
Atom Material

### **OS**
Mac

### **Tool-bar package version**
1.1.5 (latest)

### **Error description**
Failed to load the tool-bar package
variable @button-text-color-selected is undefined in /Users/$$$$/.atom/packages/tool-bar/styles/tool-bar.less:37:13

**Comment by UnConundrum** [comment]
ditto

**Comment by suda** [comment]
Oh it seems to be an issue when using `atom-material-ui` theme. I'll fix it asap

**Comment by pvdlg** [comment]
I don't use `atom-material-ui` but I still have the issue. I'm using the Atom light UI (the default one).

**Comment by edreesen** [comment]
I just manually removed the changes from PR #177 and everything works fine again.

**Comment by suda** [comment]
I'm very sorry for introducing this bug! I just released 1.1.6 which should resolve it!

**Comment by edreesen** [comment]
works fine again, thx! :) 👍

**Comment by MaxGraey** [comment]
Yep, thanks!
