### ISSUE TITLE
Update all Icon Sets

### ISSUE THREAD

**Issue by amucinom** [suda/tool-bar#226]
It'd be awesome if we could update all the icon sets to their latest versions. I know that `devicons` is missing some new icons. I will try and make a PR with updated sets!

**Comment by suda** [comment]
Thanks Aldo, that would be great! Please do!

**Comment by unluisco** [comment]
@suda Can I work in the octicons PR?

**Comment by suda** [comment]
The Octicons are bundled with Atom, so they are not controlled by this package. You can update [any other icon sets](https://github.com/suda/tool-bar/tree/master/iconsets) though! :)

**Comment by unluisco** [comment]
Thanks, I will work on this tomorrow.
also, how can I change the icons in the tool-bar-main package and use the octicons set?

**Comment by suda** [comment]
They are all declared in [this file](https://github.com/suda/tool-bar-main/blob/master/lib/tool-bar-main.coffee#L13) but IDK if Octicons have all the necessary icons for it.
