### ISSUE TITLE
Duplicate items in toolbar

### ISSUE THREAD

**Issue by saizai** [suda/tool-bar#231]
Not sure what's creating this, but here's a screenshot. LMK what debug info would be useful & how to get it.

![screen shot 2018-04-16 at 12 10 23](https://user-images.githubusercontent.com/40273/38805856-4bb5ff46-416f-11e8-86d4-ae12012f37b1.png)

**Comment by suda** [comment]
Oh that would be an issue for the package that adds those icons and not cleans up after itself, namely [doesn't remove](https://github.com/suda/tool-bar#removeitems) added buttons when restarting/updating. You can try disabling potential packages and reload Atom window to see which one is the offender and then report it on their repo :)
