### ISSUE TITLE
It's time to update the icon.woff files

### ISSUE THREAD

**Issue by NicklasVraa** [suda/tool-bar#236]
It's time to update the icon.woff files and the corresponding css. Many of the icons, referenced in the readme, arent usable, due to the woff's being outdated, e.g. the material-design-icons (mdi). Here is an updated woff.
https://github.com/Templarian/MaterialDesign-Webfont/blob/master/fonts/materialdesignicons-webfont.woff

**Comment by suda** [comment]
Hi! Could you create a PR with the updated MDI iconset? It would help greatly :)

**Comment by unluisco** [comment]
@suda we can close this issue since #247 fix this, and we can use #226 to follow progress with the other sets.

**Comment by suda** [comment]
Good call! Thanks Luis!
