### ISSUE TITLE
Keep adding buttons in sync with Status Bar package Build Status

### ISSUE THREAD

**Issue by jerone** [suda/tool-bar#24]
The [commands to add items](https://github.com/atom/status-bar/blob/master/lib/main.coffee#L18-L32) to the Status Bar changed from (append|prepend)(Left|Right) to `addLeftTile({item, priority})` and `addRightTile({item, priority})` instead.

Wondering if Toolbar should follow suit...

**Comment by suda** [comment]
I would say so. I also wanted to implement [service-hub](https://github.com/atom/service-hub) provider and then deprecate current API.

**Comment by jerone** [comment]
That definitely sound like a good idea to implement. Specially now that adoption of the toolbar isn't that high (yet!).

Do you have any plans to implement this (or some snippets in a separate branch)? I might have some spare time this week, but I have to familiarize myself with that provider first. Am relative new to Atom packages and CoffeeScript.

**Comment by suda** [comment]
@jerone I didn't started yet, but if you would like to give it a try it would be awesome!

**Comment by jerone** [comment]
@suda Just to let you know, I started working on this today, with some great success already. Will probably be this weekend when I have time to finish it.

Note to self:
* http://blog.atom.io/2015/03/25/new-services-API.html
* https://atom.io/docs/latest/behind-atom-interacting-with-packages-via-services
* https://github.com/atom/status-bar/blob/master/package.json#L16-L21
* https://github.com/atom/status-bar/blob/master/lib/main.coffee#L103-L107
* https://github.com/atom/vim-mode/blob/762a480c93cc444746c1a8150b5a24db90836144/lib/vim-mode.coffee#L42-L46

**Comment by suda** [comment]
That is awesome! You're the man Jeroen :hand:

**Comment by jerone** [comment]
Progress can be followed here:
https://github.com/jerone/toolbar/tree/services-api
https://github.com/jerone/flex-toolbar/tree/services-api

**Comment by cakecatz** [comment]
:+1:

**Comment by jerone** [comment]
Fixed by https://github.com/suda/tool-bar/pull/34
