### ISSUE TITLE
clicking the icon is failing often since upgrade to 1.1.9

### ISSUE THREAD

**Issue by Pedroalbuquerque** [suda/tool-bar#244]
I have installed today the upgrade to v1.1.9 and since then clicking the icon work first time , and than failed many times. After some time the icon is reacting again.

If I use the short-cut works every time.

I am using MAC book Pro OS 10.13.6
Atom 1.30.0
PlatforIO Home 1.0.2 Core 3.6.1a1

**Comment by suda** [comment]
Hmmm @captbaritone do you think you could take this one? It might be related to #239 🤔

**Comment by captbaritone** [comment]
Could you tell me which button is failing? Ideally you could show which Atom command the button was bound to.

**Comment by Pedroalbuquerque** [comment]
Hi captbaritone, 
I am using platformIO to develop arduino sketch both for Arduino boards and ESP8266 boards.

I do not now how to configure the tool bar, just use it often to compile, upload, open terminal and Serial console.
all this buttons came configured to me when Installed PlatformIO on top of Atom.I am using it for two year now.

The behaviour just changed suddenly this week after I accepted to install some updates , one of them being tool-bar.

First time I click any of this buttons after starting Atom and loading my project, it work OK.
Common sequence would be:
click compile - work OK
click upload - work OK
click Serial monitor - work OK
change some code in sketch...
click upload (will compile and upload) - NOK

if I insist several times (6-10) in a time interval of 1 min, it will eventually work OK and next time will fail again.

I could not yet find a pattern on number of clicks, or elapsed time to have it responde again.

Meanwhile if I use the keyboard shortcut (alt+cmd+U - to upload) it will execute immediately.

let me know how I can help further,
Pedro

**Comment by captbaritone** [comment]
@Pedroalbuquerque Thanks so much for reporting this.

@suda I have a fix here: https://github.com/suda/tool-bar/pull/245 Sorry about that.

**Comment by suda** [comment]
Just released [1.1.10](https://github.com/suda/tool-bar/releases/tag/v1.1.10) with this fix :)

**Comment by Pedroalbuquerque** [comment]
Thank you so much for such a very quick fix. I will test it as soon I get home tonight.

**Comment by captbaritone** [comment]
My apologies for breaking your workflow! Thanks for the detailed report.
