### ISSUE TITLE
icons disappear after update to v.1.1.13

### ISSUE THREAD

**Issue by ptsonkov-epam** [suda/tool-bar#264]
After update to v.1.1.13 all my icons disappear. Buttons are there but icons are not visible

**Comment by ptsonkov-epam** [comment]
I figure it out. There is issue to load "ion" icons, please to fix this

**Comment by suda** [comment]
Oh I'm sorry to hear that! @ericcornelissen can you look into this?

**Comment by UziTech** [comment]
#265 is one fix for this. It just adds `md-` to any ion icon that isn't prefixed with `ios-` or `md-`

**Comment by petKitsune** [comment]
also
_[not a tool-bar bug]_
if md- does not do the trick
ion has changed some iconnames

**Comment by UziTech** [comment]
true. The best solution might just be telling people to make sure they are using the new icon names.

**Comment by ericcornelissen** [comment]
> Oh I'm sorry to hear that! ericcornelissen can you look into this?

Ah yes, my apologies, I was unaware of the notable differences between the old and new version (should have checked :sweat_smile: again, my apologies). @UziTech's solution is definitely a good starter, though, as @petKitsune points out, it might not work for all icons as some names have changed. The only solution to that, I can think of at least, is to indeed tell people they may have to change some of the names (I don't think it is feasible to provide backwards compatibility in this package).

Alternatively you may consider reverting the change in `v1.1.14` and releasing the new icons with `v2.0.0` or `v1.2.0` to signal breaking changes.


> There is issue to load "ion" icons

Not sure what this means, Atom should have no problem finding the font as there is [a test for that](https://github.com/suda/tool-bar/blob/master/spec/tool-bar-spec.js#L160).

**Comment by suda** [comment]
You're right, we can't have backward compatibility here. Ionicons now offer iOS and Material style icons and the users should be able to select which one they prefer.

I unpublished 1.1.13 and published those changes as [1.2.0](https://github.com/suda/tool-bar/releases/tag/v1.2.0) with a warning.

We'll just have to inform any affected users about this change (I don't think there's a way to do it in an automated fashion).

Thank you all for quickly jumping on this!

**Comment by AriMKatz** [comment]
I'm getting this on 1.20

**Comment by ericcornelissen** [comment]
@AriMKatz check #268 for more details on how to resolve this issue. If you still have questions you can ask it there 😉

**Comment by PernilleF** [comment]
Where in the code do I add md- for getting the icons back?

**Comment by UziTech** [comment]
The code might be part of another package.

**Comment by AriMKatz** [comment]
Thanks, @ericcornelissen, It was a late night and I misread the thread, sorry for the noise.

**Comment by ericcornelissen** [comment]
> Thanks, @ericcornelissen, It was a late night and I misread the thread, sorry for the noise.

Not a problem :wink: I'm happy to help.


> Where in the code do I add md- for getting the icons back?

@PernilleF, As @UziTech said it might be another package, are you using any other packages with tool-bar (for example [one of the ones listed here](https://github.com/suda/tool-bar#plugins))? It might be possible to edit the configuration file for the toolbar yourself, in that case open the command pallete (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> by default) and type something along the lines of "toolbar config file" and see if there is an option to edit it. Otherwise you will need to open an issue in the respective toolbar plugins (if there isn't already).

**Comment by aminya** [comment]
Adding `ios-` or `md-` doesn't help. My toolbar doesn't load at all. What should I do?
This is my package:
https://github.com/aminya/juno-toolbar-plus

**Comment by ericcornelissen** [comment]
> My toolbar doesn't load at all. What should I do?

If the toolbar doesn't load at all there is probably a different issue 🤔 Do you see any errors in the developer tools of Atom (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> or `View -> Developer -> Toggle Developer Tools`)?

If it is just a few icons that is missing, then I advice you to [look at the Ionicons documentation](https://ionicframework.com/docs/v3/ionicons/) and see if the icon still exists under the same name.

Hope that helps @aminya 🙂

**Comment by aminya** [comment]
@ericcornelissen I fixed the problem in the last version. The name of the icons was the issue causing the toolbar not to appear.
