### ISSUE TITLE
Where are the icons?

### ISSUE THREAD

**Issue by VijitCoder** [suda/tool-bar#266]
After updating to `tool-bar 1.1.13` icons disappeared!

![2019-10-03_16-36](https://user-images.githubusercontent.com/8523131/66115997-2a8e5100-e5fc-11e9-8b0b-b1b2ec26ec5b.png)

**Comment by suda** [comment]
Hi Valery, we noticed this issue after publishing the package. Ionicons changed the naming of the icons and now they are available when adding `ios-` or `md-` prefix to the icon name, depending on the style you want. I unpublished the 1.1.13 version and published it as 1.2.0 to indicate the breaking change. The main conversation was held in #264 

If you're populating those images yourself, you can add the prefixes mentioned above. If they were added by a separate package, please file an issue (or PR even) in their repo fixing this.

I'm terribly sorry for the inconvenience.

**Comment by VijitCoder** [comment]
Oh, I'm sorry. I didn't try to search the open issue, but should be. Thanks for directing me :)
