### ISSUE TITLE
some bottoms in the toolbar is not visible

### ISSUE THREAD

**Issue by PernilleF** [suda/tool-bar#269]
![Udklip](https://user-images.githubusercontent.com/56150220/66188799-7edf1280-e688-11e9-9054-c7672addae4c.PNG)

As you can see in the Picture after updating some of the Bottoms disappeared .

**Comment by suda** [comment]
Hi there! Ionicons changed the naming of the icons and now they are available when adding `ios-` or `md-` prefix to the icon name, depending on the style you want. This change was published as 1.2.0 to indicate the breaking change. The main conversation was held in #264 

If you're populating those images yourself, you can add the prefixes mentioned above. If they were added by a separate package, please file an issue (or PR even) in their repo fixing this.
