### ISSUE TITLE
Startup performance

### ISSUE THREAD

**Issue by idleberg** [suda/tool-bar#282]
I've noticed that `tool-bar` is one of the packages in my installation with slow activation time. Compared to other packages, it's not *that* bad, but I think there are simple means to improve it. Since `activationCommmands` cannot be used to improve startup performance, how would you feel about using this `activationHook`:

```json
"activationHooks": [
  "core:loaded-shell-environment"
]
```

If there are no objections, I can submit a PR.

**Comment by ericcornelissen** [comment]
@idleberg sounds good to me, I would support this :+1: 

---

_Off topic:_ Atom's documentation would benefit from mentioning this feature outside [the word count example](https://flight-manual.atom.io/hacking-atom/sections/package-word-count/#packagejson) :upside_down_face:

**Comment by idleberg** [comment]
> Off topic: Atom's documentation would benefit from mentioning this feature outside the word count example 🙃

Yes, I knew there is a hidden example but couldn't find it. So I had to search my own packages for it ;)

**Comment by idleberg** [comment]
Fixed in #283
