### ISSUE TITLE
Is it possible to add 14px into the options for icon sizes?

### ISSUE THREAD

**Issue by HintonR** [suda/tool-bar#288]
Hi there, it's just a minor thing, but since this has been seeing updates in the last couple days, I've kept having to amend the default options to allow for icon size 14. 

Maybe there's a way to set it in the default Atom stylesheet, but I'm fairly new to all of this (and Atom) so I'm not sure how I would do that or what element of Atom to modify in the sheet. (if someone could teach me, then no need to add such a feature)

Also, I noticed in the last update, a lot of new sizes have been added.... Huhuhu but not the size I use >.<; 

Thank you for the consideration! Hahaha

**Comment by aminya** [comment]
If you need 14 I can add it

**Comment by aminya** [comment]
@HintonR This is coming soon as you requested.

**Comment by HintonR** [comment]
Thank you for this :)
