### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by simurai** [suda/tool-bar#3]
I really like this package, but I guess not how it was initially intended. :wink: 

I don't really want other packages to fill up my toolbar because I might not need/want some of the icons. But what's really great about this package is that I can just configure the icons and actions myself in `Menu > Open Your Init Script`.

So maybe you could:

* add a toggle in the settings to block other packages to automatically add icons.
* mention in the README that it's possible to customize the toolbar in the init script. Maybe it's obvious to other people, but I only discovered it when I tried this package the second time.

**Comment by brpaz** [comment]
"But what's really great about this package is that I can just configure the icons and actions myself in Menu > Open Your Init Script."
@simurai can you show an example of how to configure your menu in the init script?

**Comment by simurai** [comment]
@brpaz Sure, this should add a couple icons that do some stuff.

```coffee
atom.packages.activatePackage('toolbar')
  .then (pkg) =>
    @toolbar = pkg.mainModule

    @toolbar.appendButton 'octoface', 'open-on-github:history', 'Open on GitHub'
    @toolbar.appendSpacer()
    @toolbar.appendButton 'color-mode', 'theme-toggler:toggle', 'Toggle Themes'
    @toolbar.appendButton 'paintcan', 'styleguide:show', 'Styleguide'
    @toolbar.appendSpacer()
    @toolbar.appendButton 'three-bars', 'tree-view:toggle', 'Toggle tree-view'
    @toolbar.appendSpacer()
    @toolbar.appendButton 'gear', 'settings-view:open', 'Settings'
```

Note that you need to have some of the packages installed. And the first one, "open-on-github" doesn't seem to work. I guess it's because when you click the button, it already lost focus and doesn't know which file to open. But yeah.. you can add any command that has no "focus issue". It's basically clicking buttons instead of having to remember the shortcuts.

**Comment by brpaz** [comment]
@simurai thanks. I found the answer myself some minutes ago :)
Great package btw.

**Comment by jerone** [comment]
```
atom.packages.activatePackage('toolbar')
  .then (pkg) =>
    @toolbar = pkg.mainModule
```
Above code is the **old** way. **The new way is described in the [readme](https://github.com/suda/tool-bar#integrating-tool-bar-with-your-package).**

**Comment by jerone** [comment]
I'm closing this issue in favor of https://github.com/suda/tool-bar/issues/49
