### ISSUE TITLE
Support more iconsets

### ISSUE THREAD

**Issue by jerone** [suda/tool-bar#39]
Finding the right icon isn't always that easy. When I need one I search on http://glyphsearch.com

* [x] [Font Awesome](http://fontawesome.io/) 
* [x] [Ionicons](http://ionicons.com/)
* [x] [Octicons](http://octicons.github.com/)
* [ ] [Foundation](http://zurb.com/playground/foundation-icon-fonts-3)
* [x] ~~[Glyphicons](http://glyphicons.com/)~~ Free version doesn't supply font.
* [ ] [IcoMoon](http://icomoon.io/#icons-icomoon)

**Comment by MrLoh** [comment]
I think it would be even better, to allow adding custom svg icons. I'd like to add a shortcut to the grunt plugin to my toolbar for example. Not going to find that in any icon font, but a pretty common scenario

**Comment by jerone** [comment]
[**@MrLoh**](https://github.com/MrLoh) commented on [25 mei 2015 11:59 CEST](https://github.com/suda/tool-bar/issues/39#issuecomment-105195093 "2015-05-25T09:59:51Z - Replied by Github Comment Enhancer"):
> I think it would be even better, to allow adding custom svg icons. I'd like to add a shortcut to the grunt plugin to my toolbar for example. Not going to find that in any icon font, but a pretty common scenario

Interesting idea. How did you think of referencing that icon? Atm moment only fonts are allowed.

**Comment by MrLoh** [comment]
@jerone I haven't looked at how the icons are implemented here at the moment, but just providing a path to a file shouldn't be any problem, this is all based on web technologies anywys. Maybe I'll find time to look into it and make a pull request.

**Comment by jerone** [comment]
[**@MrLoh**](https://github.com/MrLoh) commented on [26 mei 2015 01:09 CEST](https://github.com/suda/tool-bar/issues/39#issuecomment-105333276 "2015-05-25T23:09:28Z - Replied by Github Comment Enhancer"):
> @jerone I haven't looked at how the icons are implemented here at the moment, but just providing a path to a file shouldn't be any problem, this is all based on web technologies anywys. Maybe I'll find time to look into it and make a pull request.

I moved your request to another issue: https://github.com/suda/tool-bar/issues/48
