### ISSUE TITLE
Can't know what position from the ctrl+shift+p menu

### ISSUE THREAD

**Issue by luisrudge** [suda/tool-bar#40]
![image](https://cloud.githubusercontent.com/assets/941075/7754772/8dd535ac-ffc5-11e4-9018-929ac8b5e5b3.png)

**Comment by jerone** [comment]
Confirmed. 
It's because of the second `:` in the [commands](https://github.com/suda/tool-bar/blob/master/lib/tool-bar-view.coffee#L34-L43).
But I'm not sure if this is a ToolBar issue, as it is nowhere stated that multiple `:` aren't allowed in commands.

**Comment by jerone** [comment]
Trace:

1. https://github.com/atom/command-palette/blob/master/lib/command-palette-view.coffee#L44
2. https://github.com/atom/atom/blob/a5a2fb8741bdbe6ad541234c5773dd5001a11f09/src/command-registry.coffee#L134
3. https://github.com/atom/underscore-plus/blob/2046d1562896761e3c38b7a647ac30b87b46ea20/src/underscore-plus.coffee#L142

**Comment by jerone** [comment]
I submitted an issue on Atom repo https://github.com/atom/atom/issues/6893, waiting to hear if they think it's a bug or that we need to change our commands...

**Comment by jerone** [comment]
So we need to change the commands to comply to Atom commands format `namespace-name:event-name`; https://github.com/atom/atom/issues/6893#issuecomment-104401305

I suggest we use:
`tool-bar:position-top`
`tool-bar:position-right`
`tool-bar:position-bottom`
`tool-bar:position-left`

Question arises; should be keep the old commands for legacy?

cc @suda

**Comment by suda** [comment]
@jerone I don't think changing those commands would break anything. We should change them to ones suggested by you.
