### ISSUE TITLE
Buttons don't display on tool bar (OSX)

### ISSUE THREAD

**Issue by alexandref93** [suda/tool-bar#42]
I installed the package on OSX, but not appear any buttons ... you need to install something else or is it a bug?
![Print screen](https://s3.amazonaws.com/f.cl.ly/items/0Y070t213r3o2S0X2G3T/Captura%20de%20Tela%202015-05-23%20a%CC%80s%2013.32.49.png)

**Comment by christopherdwhite** [comment]
I've been trying to figure out the same thing. :)

You can get some basic buttons by installing the [tool-bar-main](https://atom.io/packages/tool-bar-main) package. 

You may be able to more easily add your own buttons by installing the [flex-tool-bar](https://atom.io/packages/flex-tool-bar) package and updating the JSON file but I haven't been able to get it to work.

I've also tried adding buttons to your Init Script file like mentioned in [this other issue](https://github.com/suda/tool-bar/issues/3#issuecomment-71372678) but it also doesn't seem to work.

**Comment by jerone** [comment]
As @christopherdwhite mentioned, you need another package that appends the buttons/spacers to the toolbar. This package is, just like the [Status Bar](https://github.com/atom/status-bar), a service for other package to consume and add buttons.

A good start is the [Main Tool Bar ](https://atom.io/packages/tool-bar-main) package, which will append some basic buttons like Open, Save and New File.

If you want more control you can use the [Flex Tool Bar](https://atom.io/packages/flex-tool-bar) package, which requires a JSON file called `toolbar.json` in the Atom root. More about that [here](https://github.com/cakecatz/flex-toolbar#readme).

> I've also tried adding buttons to your Init Script file like mentioned in this other issue but it also doesn't seem to work.

The link you mentioned is the **old** way. The new way is described in the [readme](https://github.com/suda/tool-bar#integrating-tool-bar-with-your-package).

**Comment by alexandref93** [comment]
Cool, thank's @jerone and @christopherdwhite, now I get it.

**Comment by alexandref93** [comment]
Cool, thank's @jerone  and @christopherdwhite, now I get it.

**Comment by jerone** [comment]
@suda It might be a good idea to update the readme with a better description, now that more people are looking at this package after recent mention on Atom: http://blog.atom.io/2015/05/21/new-package-roundup.html.

**Comment by alexandref93** [comment]
I agree wtih @jerone .

**Comment by christopherdwhite** [comment]
So if you aren't using the flex toolbar is the intent for users to create their own package that more-or-less mirrors the tool-bar-main?

**Comment by jerone** [comment]
[**@christopherdwhite**](https://github.com/christopherdwhite) commented on [23 mei 2015 20:45 CEST](https://github.com/suda/tool-bar/issues/42#issuecomment-104935937 "2015-05-23T18:45:18Z - Replied by Github Comment Enhancer"):
> So if you aren't using the flex toolbar is the intent for users to create their own package that more-or-less mirrors the tool-bar-main?

The intent of a service is to hook into it and use it when available. For example on the Status Bar, the package Deprecation Cop shows the amount of deprecations in the statusbar when the statusbar service is available.
The intent of this package is to copy that idea and make it possible for other packages to append a button that does something for that package. An use-case could be a button for the Markdown Preview package. 
The Flex Tool Bar takes this concept to a whole new level and makes it possible to append multiple buttons per user needs.
When this package matures, it might be a cool idea to bring it to Atom's attention.

**Comment by christopherdwhite** [comment]
Thanks Jerone, I'm still new to Atom and don't yet know too much about package development and the community, that's really helpful!

And I did get the Flex Tool Bar working, I just had a syntax error in the JSON and was too tired last night to catch it.
