### ISSUE TITLE
Shift click for alternative action

### ISSUE THREAD

**Issue by Leonick** [suda/tool-bar#44]
Suggestion, make it so shift clicking an item can execute and alternate action.
For example, shift click open would open folder/add project folder, shift click save would save as, and shift click find would find in project.

**Comment by jerone** [comment]
Aldo this is technically possible, and I can see the use-case for it, I'm not sure how to tie the callbacks to the meta keys.

How about this?
```
@toolBar.addButton
  icon: 'octoface'
  tooltip: 'Test'
  callback: 
    '': 'application:about'  // default action, without meta keys
    alt: 'application:about'
    ctrl: 'application:about'
    shift: 'application:about'
    'alt+shift': 'application:about'  // multiple keys
```

**Comment by pradyunsg** [comment]
+1 to the proposal.
