### ISSUE TITLE
Manage third-party buttons

### ISSUE THREAD

**Issue by jerone** [suda/tool-bar#49]
Third party plugins can add any buttons they want if they consume the toolbar service. Users should be able to disallow specific plugins access to the toolbar.

**Comment by jerone** [comment]
Interesting: https://github.com/atom-minimap/minimap/blob/master/lib/mixins/plugin-management.coffee

**Comment by cakecatz** [comment]
:heart_eyes:

**Comment by cakecatz** [comment]
https://github.com/atom-minimap/minimap/blob/master/lib/mixins/plugin-management.js

**Comment by jerone** [comment]
Appearently they switched from CoffeeScript to Babel. Still useful.

**Comment by cakecatz** [comment]
Would we switch to Babel?

**Comment by jerone** [comment]
Aldo that is a bit offtopic, I don't see any real benefit for putting the efford in switching to Babel. Everything works in CoffeeScript and Atom isn't actively converting their packages either. Unless you want to put your time into it. I'm +0

-------- Original Message --------
