### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by pbihler** [suda/tool-bar#56]
Requiring `$$` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{$$} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:54:11)
Object.activate (/Users/pascal/Documents/code/github-clones/toolbar/lib/toolbar.coffee:14:5)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
```

**Comment by jerone** [comment]
You probably ran an old version. This has been fixed a long time ago.

**Comment by pbihler** [comment]
Yea, I already closed the issue, since I recognized it myself :)

That happens, if you have some dev version of the plugins linked...
