### ISSUE TITLE
Support devicon

### ISSUE THREAD

**Issue by lexcast** [suda/tool-bar#58]
[Devicon](https://github.com/konpa/devicon) has icons for languages and development tools, it would be very useful for the toolbar.

**Comment by jerone** [comment]
We're open to PR.

Ref: https://github.com/suda/tool-bar/issues/39

**Comment by igorprado** [comment]
I'm using tool-bar `0.1.5` and I can't get any devicons working. Atom `0.205.0`. What I'm missing?

**Comment by jerone** [comment]
[**@igorprado**](https://github.com/igorprado) commented on [4 jun. 2015 16:04 CEST](https://github.com/suda/tool-bar/issues/58#issuecomment-108908785 "2015-06-04T14:04:40Z - Replied by Github Comment Enhancer"):
> I'm using tool-bar `0.1.5` and I can't get any devicons working. Atom `0.205.0`. What I'm missing?

What is your code?

**Comment by igorprado** [comment]
Sorry, my bad. The documentation of DevIcon is not that clear.

To make it work, I had to click on the icon (on Devicon's page) and get from the sidebar this:

```
<!-- in your body -->
<i class="devicon-nodejs-plain"></i>
```

and use just the `nodejs-plain` in the flex-tool-bar JSON file...

**Comment by jerone** [comment]
> and use just the `nodejs-plain` in the flex-tool-bar JSON file...

That's correct. :+1: If you feel our docs are not clear, please send us a PR with a better explanation.
