### ISSUE TITLE
Add own button 

### ISSUE THREAD

**Issue by cakecatz** [suda/tool-bar#72]
Currently there is no way adding custom button on third party plugin (e.g. Label Button).
So I want method to adding own button view like this.

    button = new CustomButtonView()
    @toolBar.addCustomButton button

![screen shot 2015-06-07 at 11 28 24 pm](https://cloud.githubusercontent.com/assets/6136383/8024399/f1aa798e-0d6c-11e5-8bea-d9282b147cf0.png)

**Comment by jerone** [comment]
Do mean adding a `label` to the button options or do you want a completely [different button](`https://github.com/suda/tool-bar/issues/43)?

**Comment by cakecatz** [comment]
I want a completely different button :)

**Comment by cakecatz** [comment]
I think this will allow add various button. (Not only button with text)
`Image Button`, `Wide Button`, and more :smile:

**Comment by jerone** [comment]
Ref https://github.com/suda/tool-bar/issues/43
