### ISSUE TITLE
Tool-bar not showing up in Windows version of Atom

### ISSUE THREAD

**Issue by bnb** [suda/tool-bar#74]
I'm using Windows, and the tool-bar isn't showing up. When I change the position, it moves the main view by a pixel or two in the correct direction, but nothing is really visible. Any ideas?

**Comment by jerone** [comment]
This package by itself doesn't adds any buttons as it's a service for other package to append their own buttons. You can use one of the [plugins](https://github.com/suda/tool-bar#plugins) to append buttons.
