### ISSUE TITLE
Takes 1/5 of my initial loading time.

### ISSUE THREAD

**Issue by k2b6s9j** [suda/tool-bar#78]
![screen shot 2015-06-26 at 2 52 17 pm](https://cloud.githubusercontent.com/assets/594124/8387067/febbb6a6-1c12-11e5-9c8e-93a9d0d0f0b0.png)

**Comment by jerone** [comment]
Is this consistent? Because for me it's mostly around 25ms...

A few more data would be nice too:
* Atom version
* tool-bar version
* OS
* plugins

**Comment by k2b6s9j** [comment]
It hasn't been consistent. I have a lot of packages installed, and it could've been some weird side effect of Linter development. Sorry about that.
