### ISSUE TITLE
Buttons rendering with border around them

### ISSUE THREAD

**Issue by nickgio** [suda/tool-bar#82]
There is an awkward border rendering around the buttons/ icons on the toolbar. 

It seems to be an issue at the Toolbar level, and not a plugin level, as I tested it out on 3 different toolbars. 
* Toolbar-main
* Flex Toolbar
* Toolbar Almighty

It also persists across all icons sizes. I tried with the 16, 24, & 32px variations. 

I am using the Atom Light UI theme with Base 16 syntax. 

I've attached a screenshot below to show the issue. 

![screen shot 2015-07-15 at 3 37 48 pm](https://cloud.githubusercontent.com/assets/3130626/8709444/bee30350-2b07-11e5-9bb1-66be71cf0c30.png)

**Comment by jerone** [comment]
This is part of the default theme you are using. If you don't want the "borders" you can disable them with a small user style in your Atom directory (`~/.atom/styles.less`):

```
.tool-bar button.tool-bar-btn {
      box-shadow: none;
}
```

I'm closing this issue as invalid for now as this is the default behavior for that theme. If someone has a good case for removing those box-shadows we are open for a PR. For now use above "workaround".
