### ISSUE TITLE
Open Folder Button

### ISSUE THREAD

**Issue by EntilZha** [suda/tool-bar#89]
Is it possible or be a new feature to have an open folder (as opposed to file) button? The open file button is nice, but often I need to open a project/folder and there is no button for that.

**Comment by jerone** [comment]
You probably meant to open this issue on [Main Tool Bar](https://github.com/suda/toolbar-main) package, but if you want more control of the buttons you need [Flex Tool Bar](https://atom.io/packages/flex-tool-bar) package.
