### ISSUE TITLE
Add buttons to the end of the tool bar

### ISSUE THREAD

**Issue by nunocastromartins** [suda/tool-bar#93]
Hi!

I would like to set some of the buttons (and spacers) to appear at the end of the tool bar (e.g. the "settings-related" buttons). By "end" I mean either the right side or the bottom of the tool bar, depending on its orientation.

I believe that this makes sense in order to avoid having all the buttons cluttered at the beginning. Atom's status bar, for instance, has a left and a right side. I imagined something similar for the tool-bar extension.

Thank you for the amazing work so far! :smile:

**Comment by suda** [comment]
@nunocastromartins you can achieve this by specifying `priority` when adding buttons like [in example](https://github.com/suda/tool-bar#example). Is this what you had in mind?

**Comment by nunocastromartins** [comment]
I don't think `priority` does what I mean.
What I had in mind is a way of separating the icons in two parts: left from right (when the bar is horizontal); or top from bottom (when vertical).

Icons added to the left/top part would flow from the left/top of the bar to the right/bottom.
Icons added to the right/bottom part would flow from the right/bottom of the bar to the left/top.

Something like the following:
![screenshot from 2016-01-19 02-10-55](https://cloud.githubusercontent.com/assets/8314616/12407862/fb0891a4-be52-11e5-9dda-a3667c64b6f7.png)

I don't think `priority` does this, does it? It seems to only rearrange the order of the icons.

I believe that this would remove some clutter, clearly separating two distinct sets of icons.

**Comment by suda** [comment]
Ah, something similar to `addLeftTile` / `addRightTile` in `status-bar`. That's definitely something to add!

Thanks for clarifying :)

**Comment by jerone** [comment]
We can indeed implement method names like the [status-bar](https://github.com/atom/status-bar/blob/b37cc091a481eca63b72447be0ca23fd56573d7c/lib/main.coffee#L75-L78) package or I was thinking to do something with the priority property. Everything positive will be aligned left or top, and any negative property (e.g. -50) could be aligned right or bottom.

**Comment by jamesgpearce** [comment]
^ that would work perfectly
