### ISSUE TITLE
"Tool Bar" entry in Packages menu is not sorted alphabetically, like all the other packages

### ISSUE THREAD

**Issue by daniel-pittman** [suda/tool-bar#97]
If I had to guess, I'd guess maybe a leading space or something causing it to sort oddly?  In any case, it's actually really jarring to see this one out-of-order entry right at the top of that menu.

For an image see https://www.dropbox.com/s/87u83w1af1soz3y/Screen%20Shot%202016-01-19%20at%2010.19.42.png?dl=0

![](https://cloud.githubusercontent.com/assets/55841/12566182/a1e97cb2-c3b8-11e5-9273-141f758a9149.png)

**Comment by jerone** [comment]
I'm not seeing this in Windows ...
![2016-01-19 19_44_16-](https://cloud.githubusercontent.com/assets/55841/12428482/17b3c41c-bee5-11e5-966f-6b39a08bbdb1.png)

What OS are you running?

**Comment by daniel-pittman** [comment]
Ah, that would be on OS-X, and https://github.com/suda/tool-bar/pull/98 fixes it for me.  Turns out that the `&` for the keyboard shortcut is causing the problem there.  (It's not visible, just disorders the list.)

**Comment by jerone** [comment]
The `&` follows the character used for access key or an accelerator key. As you can see in my screenshot the character immediately following the ampersand is underlined. I'm still looking into this to see if this is only used on Windows...

**Comment by jerone** [comment]
After looking at Atom's source the ampersand trick seems to be only used on [Windows](https://github.com/atom/atom/blob/master/menus/win32.cson) & [Linux](https://github.com/atom/atom/blob/master/menus/linux.cson). [Darwin](https://github.com/atom/atom/blob/master/menus/darwin.cson) (OS-x) apparently doesn't.

**Comment by jerone** [comment]
The package menu is sorted [here](https://github.com/atom/atom/blob/7d743827820969871e8724e6f353887a3ddfc105/src/menu-manager.coffee#L67) by [function here](https://github.com/atom/atom/blob/7d743827820969871e8724e6f353887a3ddfc105/src/menu-manager.coffee#L203) which [normalizes every menuitem](https://github.com/atom/atom/blob/8427196d87e06c5cda2ba9568f518539b27bb1e1/src/menu-helpers.coffee#L40), except for [Darwin](https://github.com/atom/atom/blob/8427196d87e06c5cda2ba9568f518539b27bb1e1/src/menu-helpers.coffee#L43).

**Comment by maxkorp** [comment]
It's definitely as if they expect different menus per os, but don't seem to think that through for packages

**Comment by jerone** [comment]
Indeed they don't: https://github.com/atom/atom/blob/3827b19da4e0cbc318d7541cea66c8c2a8412e8f/src/package.coffee#L267 no sign of `process.platform` :(

Conclusion; no way to define an `menus/menu.cson` file per OS. Bug or missing feature ?!

**Comment by jerone** [comment]
Tracking https://github.com/atom/atom/issues/10583
